SOLVER:
  gpu: 0,
  logdir: /media/christina/Data/ANFASS_data/O-CNN/output/ocnn_completion/ae/ae_points_ocnn_f_decode_shape
  ckpt: /media/christina/Data/ANFASS_data/O-CNN/output/ocnn_completion/ae/ae_points_ocnn_f/model/iter_147200.ckpt
  run: decode_shape
  test_iter: 43

DATA:
  test: 
    dtype: points
    depth: 6
    location: /media/christina/Data/ANFASS_data/O-CNN/ocnn_completion/specific_test_points.tfrecords
    batch_size: 1
    distort: False
    offset: 0.0
    node_dis: True
    split_label: True
    shuffle: 0

MODEL:
  name: ocnn
  channel: 4
  nout: 32   # The channel of the hidden code
  depth: 6

LOSS:
  weight_decay: 0.0005