
SOLVER:
  gpu: 0,
  logdir: /media/maria/BigData1/Maria/buildnet_data_2k/100K_inverted_normals/partnet_exp/custom_code_buildnet_step/
  max_iter: 18000 #1920000, 60 epochs
  test_iter: 50 #37
  test_every_iter: 300 #19200
  run: train
  gamma: 0.1
  learning_rate: 0.1
#  lr_type: 'plateau'
  lr_type: 'step'
  step_size: (9000,4500)
  class_weights: 'none' #./configs/class_weights.json
#  ckpt: '/media/maria/BigData1/Maria/buildnet_data_2k/100K_inverted_normals/partnet_exp/custom_code/model/iter_003000.ckpt'
#  verbose: True

DATA:
  train:
    dtype: points
    depth: 6
    axis: y
    node_dis: False
    shuffle: True
    take: -1
#    location: /media/maria/BigData1/Maria/caffe_ocnn_seg_tf/dataset/ply/
#    file_list: /media/maria/BigData1/Maria/caffe_ocnn_seg_tf/dataset/dataset/Bed_train_level3.txt
    location: /media/maria/BigData1/Maria/buildnet_data_2k/100K_inverted_normals/withcolor/
    file_list: /media/maria/BigData1/Maria/buildnet_data_2k/100K_inverted_normals/train_split_50_first.txt
    label_location: /media/maria/BigData1/Maria/buildnet_data_2k/100K_inverted_normals/point_labels_32/
    batch_size: 4 #32
    mask_ratio: 0.5
#    sigma: 0.0
#    clip: 0.0
    rot_num: 12
    return_pts: True
    use_majority: False
    hsv: False

  test: 
    dtype: points
    depth: 6
    axis: y
    node_dis: False
#    location: /media/maria/BigData1/Maria/caffe_ocnn_seg_tf/dataset/ply/
#    file_list: /media/maria/BigData1/Maria/caffe_ocnn_seg_tf/dataset/dataset/Bed_test_level3.txt
    location: /media/maria/BigData1/Maria/buildnet_data_2k/100K_inverted_normals/withcolor/
    file_list: /media/maria/BigData1/Maria/buildnet_data_2k/100K_inverted_normals/val_split_50_first.txt
    label_location: /media/maria/BigData1/Maria/buildnet_data_2k/100K_inverted_normals/point_labels_32/
    shuffle: False
    batch_size: 1
    sigma: 0.0
    return_pts: True
    use_majority: False
    hsv: False


MODEL:
  name: hrnet
  channel: 3
  nout: 31
  depth: 6
  factor: 2
  signal_abs: True
  depth_out: 6

LOSS:
  num_class: 31
  momentum: 0.9
  weight_decay: 0.0005
  point_wise: True
