# Parameters for the airplane

SOLVER:
  gpu: 0,
  logdir: /media/maria/BigData1/Maria/buildnet_data_2k/100K_inverted_normals/cluster_exp_results/Seg_2k_100k_hrnet_no_colour_depth_7_weighted_sgd_3_0.5/
  max_iter: 1200 #1920000
  test_iter: 200
  test_every_iter: 12 #19200
  run: test
  lr_type: 'plateau'
  class_weights: ./configs/class_weights.json
  #step_size: (1500, 750)
  ckpt: '/media/maria/BigData1/Maria/buildnet_data_2k/100K_inverted_normals/cluster_exp_results/Seg_2k_100k_hrnet_no_colour_depth_7_weighted_sgd_3_0.5/best_ckpts/epoch48.ckpt'
  verbose: True

DATA:
  train:
    dtype: points
    distort: False #True
    depth: 7
    axis: y 
#    angle: (5, 5, 5)
#    interval: (1, 1, 1)
#    scale: 0.25
#    jitter: 0.125
#    offset: 0.0
#    uniform: True
    node_dis: False
    shuffle: True
    take: -1
    location: /media/maria/BigData1/Maria/buildnet_data_2k/100K_inverted_normals/nocolor/
    file_list: /media/maria/BigData1/Maria/buildnet_data_2k/100K_inverted_normals/majority_test.txt #train_split.txt
    label_location: /media/maria/BigData1/Maria/buildnet_data_2k/100K_inverted_normals/point_labels_32/
    batch_size: 1
    x_alias: data
    mask_ratio: 0.0
    return_pts: True
    use_majority: False

  test: 
    dtype: points
    distort: False  # no data augmentation
    depth: 7
    axis: y
#    angle: (1, 1, 1)
#    interval: (1, 1, 1)
#    scale: 0.25
#    jitter: 0.25
#    offset: 0.0
    node_dis: False
    location: /media/maria/BigData1/Maria/buildnet_data_2k/100K_inverted_normals/nocolor/
    file_list: /media/maria/BigData1/Maria/buildnet_data_2k/100K_inverted_normals/test_split.txt #val_split.txt
    label_location: /media/maria/BigData1/Maria/buildnet_data_2k/100K_inverted_normals/point_labels_32/
    shuffle: False
    batch_size: 1
    x_alias: data
    return_pts: True


MODEL:
  name: hrnet
  channel: 3
  nout: 31
  depth: 7
  factor: 2
  signal_abs: True
  depth_out: 7

LOSS:
  num_class: 31
  momentum: 0.9
  weight_decay: 0.0005
  point_wise: True
